# Generated by Django 4.2.7 on 2023-12-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registrationotpmodel_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='acc_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('BUSINESS', 'Business')], default='PERSONAL', max_length=25),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
