# Generated by Django 4.2.7 on 2023-12-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userinformation_acc_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPModel',
        ),
    ]
