# Generated by Django 4.2.7 on 2024-01-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userfirebasetoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfirebasetoken',
            options={'ordering': ('user',)},
        ),
    ]
