# Generated by Django 4.2.7 on 2024-01-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userfirebasetoken_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationotpmodel',
            old_name='device_id',
            new_name='device_token',
        ),
    ]
