# Generated by Django 4.2.7 on 2024-01-17 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_device_id_registrationotpmodel_device_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='device_id',
            new_name='device_token',
        ),
    ]
