# Generated by Django 4.2.7 on 2024-03-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_registrationotpmodel_is_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='profile_pic_hash',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
