# Generated by Django 4.2.7 on 2023-12-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_appfeedback_rating_alter_userrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appfeedback',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
    ]
