# Generated by Django 4.2.7 on 2023-12-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_appfeedback_rating_alter_userrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appfeedback',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
