# Generated by Django 4.2.7 on 2023-12-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_appfeedback_rating_alter_userrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='provider_response_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
