# Generated by Django 4.2.7 on 2024-01-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_analytics_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='no_of_transaction',
            field=models.IntegerField(default=0),
        ),
    ]
