# Generated by Django 4.2.7 on 2024-02-29 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0008_userrating_no_of_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSeekerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('no_of_transaction', models.IntegerField(default=0)),
                ('deal_success_rate', models.FloatField(default=0.0)),
                ('total_amount_of_transaction', models.FloatField(default=0.0)),
                ('dislikes', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_rating_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
