# Generated by Django 4.2.7 on 2024-03-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_alter_userseekerrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='abuse_report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userseekerrating',
            name='abuse_report_count',
            field=models.IntegerField(default=0),
        ),
    ]
