# Generated by Django 4.2.7 on 2023-12-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_socket', '0002_room_chathistory_callhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callhistory',
            options={'ordering': ('room', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ('room', '-created_at')},
        ),
    ]
