# Generated by Django 4.2.7 on 2023-12-27 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_socket', '0003_alter_callhistory_options_alter_chathistory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationradius',
            name='user_location',
        ),
        migrations.AddField(
            model_name='locationradius',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_location_radius', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
