# Generated by Django 4.2.7 on 2023-12-28 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_socket', '0004_remove_locationradius_user_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='user',
        ),
        migrations.DeleteModel(
            name='LocationRadius',
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
