# Generated by Django 4.2.7 on 2024-01-02 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_socket', '0006_alter_callhistory_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocketRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_provider', to=settings.AUTH_USER_MODEL)),
                ('seeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_seeker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='room',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='room',
            name='seeker',
        ),
        migrations.DeleteModel(
            name='CallHistory',
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
