# Generated by Django 4.2.7 on 2024-01-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_socket', '0009_transactionmessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socketroom',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='socketroom',
            name='seeker',
        ),
        migrations.DeleteModel(
            name='RoomMessages',
        ),
        migrations.DeleteModel(
            name='SocketRoom',
        ),
    ]
