# Generated by Django 4.2.7 on 2024-02-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_socket', '0010_remove_socketroom_provider_remove_socketroom_seeker_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionMessages',
        ),
    ]
