# Generated by Django 4.2.7 on 2024-09-25 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserCredits",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "credit_as_seeker",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
            ],
            options={
                "ordering": ("user",),
            },
        ),
    ]
