# Generated by Django 4.2.7 on 2024-09-25 09:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("txn_credits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccumulatedCredits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("credit_as_seeker", models.FloatField(default=0)),
                ("credit_as_provider", models.FloatField(default=0)),
            ],
            options={
                "ordering": ("user",),
            },
        ),
        migrations.CreateModel(
            name="CreditUser",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user_uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ("user_uid",),
            },
        ),
        migrations.CreateModel(
            name="TxnCredits",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("txn_id", models.IntegerField(primary_key=True, serialize=False)),
                ("charge", models.FloatField(default=0)),
                ("credit", models.FloatField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="UserCredits",
        ),
        migrations.AddField(
            model_name="accumulatedcredits",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="txn_credits.credituser"
            ),
        ),
    ]
