# Generated by Django 4.2.7 on 2024-09-26 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("txn_credits", "0003_delete_txncredits"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderTxnPlatform",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("transaction", models.IntegerField(primary_key=True, serialize=False)),
                ("profit", models.FloatField(default=0.0)),
                ("platform_fee", models.FloatField(default=0.0)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="txn_platforms_provider",
                        to="txn_credits.credituser",
                    ),
                ),
            ],
            options={
                "ordering": ("transaction",),
            },
        ),
        migrations.CreateModel(
            name="PlatformReceivable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("amount", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platforms_receivable_user",
                        to="txn_credits.credituser",
                    ),
                ),
            ],
            options={
                "ordering": ("user",),
            },
        ),
    ]
