# Generated by Django 4.2.7 on 2023-12-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionreview',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
