# Generated by Django 4.2.7 on 2023-12-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_userservicemode_digitalwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionreview',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
