# Generated by Django 4.2.7 on 2023-12-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
