# Generated by Django 4.2.7 on 2024-01-10 05:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0004_alter_transaction_preferred_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('preferred_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None)),
                ('is_affirmed', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction_provider', to=settings.AUTH_USER_MODEL)),
                ('seeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction_seeker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('seeker',),
            },
        ),
    ]
