# Generated by Django 4.2.7 on 2024-01-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transactionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrequest',
            name='request_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15),
        ),
    ]
