# Generated by Django 4.2.7 on 2024-01-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transactionrequest_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionrequest',
            name='is_affirmed',
        ),
    ]
