# Generated by Django 4.2.7 on 2024-01-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_userservicemode_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_no',
        ),
    ]
