# Generated by Django 4.2.7 on 2024-01-18 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_remove_transaction_transaction_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-created_at', '-id')},
        ),
    ]
