# Generated by Django 4.2.7 on 2024-01-30 06:02

from django.db import migrations, models
import utils.helper


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_rename_request_status_transactionrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.helper.content_file_path),
        ),
    ]
