# Generated by Django 4.2.7 on 2024-01-30 10:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_transaction_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='preferred_notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='preferred_notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None),
        ),
    ]
