# Generated by Django 4.2.7 on 2024-02-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_transaction_preferred_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_pin',
            field=models.IntegerField(default=0),
        ),
    ]
