# Generated by Django 4.2.7 on 2024-02-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_transaction_transaction_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_pin',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
