# Generated by Django 4.2.7 on 2024-02-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_alter_transaction_transaction_pin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionRequest',
        ),
    ]
