# Generated by Django 4.2.7 on 2024-02-29 05:42

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0018_transactionmessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('transaction', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.FloatField(default=0, null=True)),
                ('preferred_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), size=None)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_transaction_provider', to=settings.AUTH_USER_MODEL)),
                ('seeker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_transaction_seeker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
