# Generated by Django 4.2.7 on 2024-02-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_usertransactionresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransactionresponse',
            name='request_time',
        ),
    ]
