# Generated by Django 4.2.7 on 2024-02-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_alter_usertransactionresponse_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactionresponse',
            name='response_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
