# Generated by Django 4.2.7 on 2024-03-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_transactionhistory_provider_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='qr_image_hash',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
