# Generated by Django 4.2.7 on 2024-03-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_transaction_qr_image_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionmessages',
            options={'ordering': ('-created_at', 'transaction')},
        ),
        migrations.AddField(
            model_name='transactionmessages',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
