# Generated by Django 4.2.7 on 2024-03-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_alter_transactionmessages_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='provider_location',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='seeker_location',
        ),
    ]
