# Generated by Django 4.2.7 on 2024-09-23 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0030_userappactivitymode"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionasproviderabusereport",
            name="seeker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="txn_prov_abuse_rep_seeker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transactionasproviderreview",
            name="seeker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="txn_provider_review_seeker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transactionasseekerabusereport",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="txn_seek_abuse_rep_provider",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transactionasseekerreview",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="txn_seeker_review_provider",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
