# Generated by Django 4.2.7 on 2024-01-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_userlocation_alter_locationradius_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
