# Generated by Django 4.2.7 on 2024-01-01 11:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.gis.geos import Point


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_userlocation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='centre',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(1,1), srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='latitude',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='longitude',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
