# Generated by Django 4.2.7 on 2024-01-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_userlocation_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.UUIDField(unique=True),
        ),
    ]
