# Generated by Django 4.2.7 on 2024-01-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_userlocation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='user_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
