# Generated by Django 4.2.7 on 2024-01-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_userlocation_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationRadius',
        ),
    ]
