# Generated by Django 4.2.7 on 2024-01-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_delete_locationradius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='latitude',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='longitude',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
