# Generated by Django 4.2.7 on 2024-02-10 06:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_alter_userlocation_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolyLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linestring', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
