# Generated by Django 4.2.7 on 2024-02-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_polyline_point_alter_polyline_linestring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polyline',
            name='point',
        ),
        migrations.AddField(
            model_name='polyline',
            name='provider',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polyline',
            name='seeker',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
