# Generated by Django 4.2.7 on 2024-02-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_remove_polyline_point_polyline_provider_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polyline',
            options={'ordering': ('transaction',)},
        ),
        migrations.RemoveField(
            model_name='polyline',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='polyline',
            name='seeker',
        ),
        migrations.AddField(
            model_name='polyline',
            name='transaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
