# Generated by Django 4.2.7 on 2024-03-05 04:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_alter_polyline_options_remove_polyline_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polyline',
            name='provider_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='polyline',
            name='seeker_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
