# Generated by Django 4.2.7 on 2024-01-14 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VangtiTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('terms_and_conditions', models.FileField(blank=True, null=True, upload_to=utils.helper.content_file_path)),
                ('privacy_policy', models.FileField(blank=True, null=True, upload_to=utils.helper.content_file_path)),
                ('about', models.FileField(blank=True, null=True, upload_to=utils.helper.content_file_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('BANGLA', 'Bangla')], default='ENGLISH', max_length=10)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('accepted_timestamp', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
